//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 02:17:59 AM BDT 
//


package com.healthcare.ws.inventorymanagementservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.healthcare.ws.inventorymanagementservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InventoryFault_QNAME = new QName("http://www.healthcare.com/ws/InventoryManagementService", "inventoryFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.healthcare.ws.inventorymanagementservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddInventoryRequest }
     * 
     */
    public AddInventoryRequest createAddInventoryRequest() {
        return new AddInventoryRequest();
    }

    /**
     * Create an instance of {@link InventoryItem }
     * 
     */
    public InventoryItem createInventoryItem() {
        return new InventoryItem();
    }

    /**
     * Create an instance of {@link AddInventoryResponse }
     * 
     */
    public AddInventoryResponse createAddInventoryResponse() {
        return new AddInventoryResponse();
    }

    /**
     * Create an instance of {@link StatusCode }
     * 
     */
    public StatusCode createStatusCode() {
        return new StatusCode();
    }

    /**
     * Create an instance of {@link UpdateInventoryRequest }
     * 
     */
    public UpdateInventoryRequest createUpdateInventoryRequest() {
        return new UpdateInventoryRequest();
    }

    /**
     * Create an instance of {@link UpdateInventoryResponse }
     * 
     */
    public UpdateInventoryResponse createUpdateInventoryResponse() {
        return new UpdateInventoryResponse();
    }

    /**
     * Create an instance of {@link GetInventoryRequest }
     * 
     */
    public GetInventoryRequest createGetInventoryRequest() {
        return new GetInventoryRequest();
    }

    /**
     * Create an instance of {@link GetInventoryResponse }
     * 
     */
    public GetInventoryResponse createGetInventoryResponse() {
        return new GetInventoryResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.healthcare.com/ws/InventoryManagementService", name = "inventoryFault")
    public JAXBElement<String> createInventoryFault(String value) {
        return new JAXBElement<String>(_InventoryFault_QNAME, String.class, null, value);
    }

}
