//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 01:56:04 AM BDT 
//


package com.healthcare.ws.notificationservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.healthcare.ws.notificationservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NotificationFault_QNAME = new QName("http://www.healthcare.com/ws/NotificationService", "notificationFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.healthcare.ws.notificationservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendNotificationRequest }
     * 
     */
    public SendNotificationRequest createSendNotificationRequest() {
        return new SendNotificationRequest();
    }

    /**
     * Create an instance of {@link NotificationType }
     * 
     */
    public NotificationType createNotificationType() {
        return new NotificationType();
    }

    /**
     * Create an instance of {@link SendNotificationResponse }
     * 
     */
    public SendNotificationResponse createSendNotificationResponse() {
        return new SendNotificationResponse();
    }

    /**
     * Create an instance of {@link StatusCode }
     * 
     */
    public StatusCode createStatusCode() {
        return new StatusCode();
    }

    /**
     * Create an instance of {@link UpdateNotificationRequest }
     * 
     */
    public UpdateNotificationRequest createUpdateNotificationRequest() {
        return new UpdateNotificationRequest();
    }

    /**
     * Create an instance of {@link UpdateNotificationResponse }
     * 
     */
    public UpdateNotificationResponse createUpdateNotificationResponse() {
        return new UpdateNotificationResponse();
    }

    /**
     * Create an instance of {@link GetNotificationsRequest }
     * 
     */
    public GetNotificationsRequest createGetNotificationsRequest() {
        return new GetNotificationsRequest();
    }

    /**
     * Create an instance of {@link GetNotificationsResponse }
     * 
     */
    public GetNotificationsResponse createGetNotificationsResponse() {
        return new GetNotificationsResponse();
    }

    /**
     * Create an instance of {@link NotificationTypes }
     * 
     */
    public NotificationTypes createNotificationTypes() {
        return new NotificationTypes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.healthcare.com/ws/NotificationService", name = "notificationFault")
    public JAXBElement<String> createNotificationFault(String value) {
        return new JAXBElement<String>(_NotificationFault_QNAME, String.class, null, value);
    }

}
