//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.25 at 11:45:41 AM BDT 
//


package com.healthcare.ws.medicalrecordservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.healthcare.ws.medicalrecordservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MedicalRecordFault_QNAME = new QName("http://www.healthcare.com/ws/MedicalRecordService", "medicalRecordFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.healthcare.ws.medicalrecordservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateMedicalRecordRequest }
     * 
     */
    public CreateMedicalRecordRequest createCreateMedicalRecordRequest() {
        return new CreateMedicalRecordRequest();
    }

    /**
     * Create an instance of {@link MedicalRecordType }
     * 
     */
    public MedicalRecordType createMedicalRecordType() {
        return new MedicalRecordType();
    }

    /**
     * Create an instance of {@link CreateMedicalRecordResponse }
     * 
     */
    public CreateMedicalRecordResponse createCreateMedicalRecordResponse() {
        return new CreateMedicalRecordResponse();
    }

    /**
     * Create an instance of {@link StatusCode }
     * 
     */
    public StatusCode createStatusCode() {
        return new StatusCode();
    }

    /**
     * Create an instance of {@link UpdateMedicalRecordRequest }
     * 
     */
    public UpdateMedicalRecordRequest createUpdateMedicalRecordRequest() {
        return new UpdateMedicalRecordRequest();
    }

    /**
     * Create an instance of {@link UpdateMedicalRecordResponse }
     * 
     */
    public UpdateMedicalRecordResponse createUpdateMedicalRecordResponse() {
        return new UpdateMedicalRecordResponse();
    }

    /**
     * Create an instance of {@link GetMedicalRecordsRequest }
     * 
     */
    public GetMedicalRecordsRequest createGetMedicalRecordsRequest() {
        return new GetMedicalRecordsRequest();
    }

    /**
     * Create an instance of {@link GetMedicalRecordsResponse }
     * 
     */
    public GetMedicalRecordsResponse createGetMedicalRecordsResponse() {
        return new GetMedicalRecordsResponse();
    }

    /**
     * Create an instance of {@link MedicalRecordTypes }
     * 
     */
    public MedicalRecordTypes createMedicalRecordTypes() {
        return new MedicalRecordTypes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.healthcare.com/ws/MedicalRecordService", name = "medicalRecordFault")
    public JAXBElement<String> createMedicalRecordFault(String value) {
        return new JAXBElement<String>(_MedicalRecordFault_QNAME, String.class, null, value);
    }

}
