//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 01:43:57 AM BDT 
//


package com.healthcare.ws.billingservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.healthcare.ws.billingservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BillingFault_QNAME = new QName("http://www.healthcare.com/ws/BillingService", "billingFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.healthcare.ws.billingservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateInvoiceRequest }
     * 
     */
    public CreateInvoiceRequest createCreateInvoiceRequest() {
        return new CreateInvoiceRequest();
    }

    /**
     * Create an instance of {@link InvoiceType }
     * 
     */
    public InvoiceType createInvoiceType() {
        return new InvoiceType();
    }

    /**
     * Create an instance of {@link CreateInvoiceResponse }
     * 
     */
    public CreateInvoiceResponse createCreateInvoiceResponse() {
        return new CreateInvoiceResponse();
    }

    /**
     * Create an instance of {@link StatusCode }
     * 
     */
    public StatusCode createStatusCode() {
        return new StatusCode();
    }

    /**
     * Create an instance of {@link UpdateInvoiceRequest }
     * 
     */
    public UpdateInvoiceRequest createUpdateInvoiceRequest() {
        return new UpdateInvoiceRequest();
    }

    /**
     * Create an instance of {@link UpdateInvoiceResponse }
     * 
     */
    public UpdateInvoiceResponse createUpdateInvoiceResponse() {
        return new UpdateInvoiceResponse();
    }

    /**
     * Create an instance of {@link GetInvoicesRequest }
     * 
     */
    public GetInvoicesRequest createGetInvoicesRequest() {
        return new GetInvoicesRequest();
    }

    /**
     * Create an instance of {@link GetInvoicesResponse }
     * 
     */
    public GetInvoicesResponse createGetInvoicesResponse() {
        return new GetInvoicesResponse();
    }

    /**
     * Create an instance of {@link InvoiceTypes }
     * 
     */
    public InvoiceTypes createInvoiceTypes() {
        return new InvoiceTypes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.healthcare.com/ws/BillingService", name = "billingFault")
    public JAXBElement<String> createBillingFault(String value) {
        return new JAXBElement<String>(_BillingFault_QNAME, String.class, null, value);
    }

}
