<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ReportGenerationService"
             targetNamespace="http://www.healthcare.com/ws/ReportGenerationService"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.healthcare.com/ws/ReportGenerationService">

    <types>
        <xs:schema>
        <xs:import namespace="http://www.healthcare.com/ws/ReportGenerationService" schemaLocation="../schemas/ReportGenerationServiceSchema.xsd"/>
        </xs:schema>
    </types>

    <message name="reportFault">
        <part name="params" element="tns:reportFault"/>
    </message>

    <message name="generateReportRequestMsg">
        <part name="params" element="tns:generateReportRequest"/>
    </message>
    <message name="generateReportResponseMsg">
        <part name="params" element="tns:generateReportResponse"/>
    </message>

    <portType name="ReportGenerationServicePortType">
        <operation name="generateReport">
            <input message="tns:generateReportRequestMsg"/>
            <output message="tns:generateReportResponseMsg"/>
            <fault name="fault" message="tns:reportFault"/>
        </operation>
    </portType>

    <binding name="reportGenerationServiceSOAPBinding" type="tns:ReportGenerationServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="generateReport">
            <soap:operation soapAction="generateReport"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal"/>
            </fault>
        </operation>
    </binding>

    <service name="ReportGenerationService">
        <port name="ReportGenerationServicePort" binding="tns:reportGenerationServiceSOAPBinding">
            <soap:address location="http://localhost:8086/wsdlfirst/reportGenerationService"/>
        </port>
    </service>
</definitions>
