//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.25 at 12:03:22 AM BDT 
//


package com.healthcare.ws.patientservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.healthcare.ws.patientservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PatientFault_QNAME = new QName("http://www.healthcare.com/ws/PatientService", "patientFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.healthcare.ws.patientservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterPatientRequest }
     * 
     */
    public RegisterPatientRequest createRegisterPatientRequest() {
        return new RegisterPatientRequest();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientType();
    }

    /**
     * Create an instance of {@link RegisterPatientResponse }
     * 
     */
    public RegisterPatientResponse createRegisterPatientResponse() {
        return new RegisterPatientResponse();
    }

    /**
     * Create an instance of {@link StatusCode }
     * 
     */
    public StatusCode createStatusCode() {
        return new StatusCode();
    }

    /**
     * Create an instance of {@link UpdatePatientRequest }
     * 
     */
    public UpdatePatientRequest createUpdatePatientRequest() {
        return new UpdatePatientRequest();
    }

    /**
     * Create an instance of {@link UpdatePatientResponse }
     * 
     */
    public UpdatePatientResponse createUpdatePatientResponse() {
        return new UpdatePatientResponse();
    }

    /**
     * Create an instance of {@link GetPatientDetailsRequest }
     * 
     */
    public GetPatientDetailsRequest createGetPatientDetailsRequest() {
        return new GetPatientDetailsRequest();
    }

    /**
     * Create an instance of {@link GetPatientDetailsResponse }
     * 
     */
    public GetPatientDetailsResponse createGetPatientDetailsResponse() {
        return new GetPatientDetailsResponse();
    }

    /**
     * Create an instance of {@link DeletePatientRequest }
     * 
     */
    public DeletePatientRequest createDeletePatientRequest() {
        return new DeletePatientRequest();
    }

    /**
     * Create an instance of {@link DeletePatientResponse }
     * 
     */
    public DeletePatientResponse createDeletePatientResponse() {
        return new DeletePatientResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.healthcare.com/ws/PatientService", name = "patientFault")
    public JAXBElement<String> createPatientFault(String value) {
        return new JAXBElement<String>(_PatientFault_QNAME, String.class, null, value);
    }

}
