//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 02:01:21 AM BDT 
//


package com.healthcare.ws.reportgenerationservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.healthcare.ws.reportgenerationservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReportFault_QNAME = new QName("http://www.healthcare.com/ws/ReportGenerationService", "reportFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.healthcare.ws.reportgenerationservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenerateReportRequest }
     * 
     */
    public GenerateReportRequest createGenerateReportRequest() {
        return new GenerateReportRequest();
    }

    /**
     * Create an instance of {@link GenerateReportResponse }
     * 
     */
    public GenerateReportResponse createGenerateReportResponse() {
        return new GenerateReportResponse();
    }

    /**
     * Create an instance of {@link StatusCode }
     * 
     */
    public StatusCode createStatusCode() {
        return new StatusCode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.healthcare.com/ws/ReportGenerationService", name = "reportFault")
    public JAXBElement<String> createReportFault(String value) {
        return new JAXBElement<String>(_ReportFault_QNAME, String.class, null, value);
    }

}
