//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.25 at 11:17:24 AM BDT 
//


package com.healthcare.ws.doctorservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.healthcare.ws.doctorservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DoctorFault_QNAME = new QName("http://www.healthcare.com/ws/DoctorService", "doctorFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.healthcare.ws.doctorservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateDoctorRequest }
     * 
     */
    public UpdateDoctorRequest createUpdateDoctorRequest() {
        return new UpdateDoctorRequest();
    }

    /**
     * Create an instance of {@link DoctorType }
     * 
     */
    public DoctorType createDoctorType() {
        return new DoctorType();
    }

    /**
     * Create an instance of {@link UpdateDoctorResponse }
     * 
     */
    public UpdateDoctorResponse createUpdateDoctorResponse() {
        return new UpdateDoctorResponse();
    }

    /**
     * Create an instance of {@link StatusCode }
     * 
     */
    public StatusCode createStatusCode() {
        return new StatusCode();
    }

    /**
     * Create an instance of {@link DeleteDoctorRequest }
     * 
     */
    public DeleteDoctorRequest createDeleteDoctorRequest() {
        return new DeleteDoctorRequest();
    }

    /**
     * Create an instance of {@link DeleteDoctorResponse }
     * 
     */
    public DeleteDoctorResponse createDeleteDoctorResponse() {
        return new DeleteDoctorResponse();
    }

    /**
     * Create an instance of {@link GetDoctorsRequest }
     * 
     */
    public GetDoctorsRequest createGetDoctorsRequest() {
        return new GetDoctorsRequest();
    }

    /**
     * Create an instance of {@link GetDoctorsResponse }
     * 
     */
    public GetDoctorsResponse createGetDoctorsResponse() {
        return new GetDoctorsResponse();
    }

    /**
     * Create an instance of {@link DoctorTypes }
     * 
     */
    public DoctorTypes createDoctorTypes() {
        return new DoctorTypes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.healthcare.com/ws/DoctorService", name = "doctorFault")
    public JAXBElement<String> createDoctorFault(String value) {
        return new JAXBElement<String>(_DoctorFault_QNAME, String.class, null, value);
    }

}
