//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.25 at 11:17:24 AM BDT 
//


package com.healthcare.ws.doctorservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="doctorType" type="{http://www.healthcare.com/ws/DoctorService}DoctorType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "doctorType"
})
@XmlRootElement(name = "updateDoctorRequest")
public class UpdateDoctorRequest {

    @XmlElement(required = true)
    protected DoctorType doctorType;

    /**
     * Gets the value of the doctorType property.
     * 
     * @return
     *     possible object is
     *     {@link DoctorType }
     *     
     */
    public DoctorType getDoctorType() {
        return doctorType;
    }

    /**
     * Sets the value of the doctorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoctorType }
     *     
     */
    public void setDoctorType(DoctorType value) {
        this.doctorType = value;
    }

}
