//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.02 at 02:11:16 AM BDT 
//


package com.healthcare.ws.loggingservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.healthcare.ws.loggingservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LogFault_QNAME = new QName("http://www.healthcare.com/ws/LoggingService", "logFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.healthcare.ws.loggingservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LogMessageRequest }
     * 
     */
    public LogMessageRequest createLogMessageRequest() {
        return new LogMessageRequest();
    }

    /**
     * Create an instance of {@link LogMessageResponse }
     * 
     */
    public LogMessageResponse createLogMessageResponse() {
        return new LogMessageResponse();
    }

    /**
     * Create an instance of {@link StatusCode }
     * 
     */
    public StatusCode createStatusCode() {
        return new StatusCode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.healthcare.com/ws/LoggingService", name = "logFault")
    public JAXBElement<String> createLogFault(String value) {
        return new JAXBElement<String>(_LogFault_QNAME, String.class, null, value);
    }

}
