//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.25 at 11:36:22 AM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.healthcare.com/ws/AppointmentService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.healthcare.ws.appointmentservice;
